title:              "Glett's something cheerful"
tagline:            ""
email:              "baesya@gmail.com"
description:        "The way I can express all of my life."
author:             "Glet Bae"
baseurl:            "/"
url:                "https://glett.kr"
locale:             "ko_KR"
thumbnail:          "/img/bg-thumnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

  # 블로그 disqus shortname
disqus:
  shortname: http-glett-kr
